on : push
name: 🚀 Deploy website on push to AlwaysData
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Install npm dependencies
        run: npm install
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ssh-ecoridefront.alwaysdata.net
          protocol: ftps
          port: 22
          username: ecoridefront
          password: ${{ secrets.FTP_PASSWORD_ALWAYSDATA }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/bootstrap/scss/**
            **/node_modules/bootstrap/js/**
            **/node_modules/bootstrap-icons/icons/**  
          server-dir: /www/
          dry-run: true
          timeout: 60000
          log-level: verbose
          
